# Generated by Django 5.0.6 on 2024-05-13 08:23

import django.db.models.deletion
import managers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Department Manager', max_length=100)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.ImageField(blank=True, default='assets/images/default_account.png', null=True, upload_to=managers.models.manager_avatar_upload_to)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'middle_name', 'user__last_name'],
            },
        ),
    ]
