# Generated by Django 5.0.6 on 2024-05-13 08:23

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_image', models.ImageField(blank=True, default='assets/images/default_certificate.jpg', null=True, upload_to=certificates.models.certificate_upload_to)),
                ('student_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='students.student')),
                ('teacher_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date_earned', 'organization', 'certificate_name'],
            },
        ),
    ]
